version: '3.8'

services:
  database:
    container_name: housemate_db
    image: mongo:latest
    volumes:
      - mongodbdata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro  # script for adding a user for the app
    environment:
      - MONGO_INITDB_DATABASE=houseDB
      # you can access to the db via "$ mongosh -u houseAdmin -p housePassAdmin"
      - MONGO_INITDB_ROOT_USERNAME=houseAdmin
      - MONGO_INITDB_ROOT_PASSWORD=housePassAdmin
    command: mongod --auth
    ports:
      - '27017:27017'


  server:
    container_name: housemate_backend
    build: ./backend
    environment:
      - MONGODB_URL=mongodb://houseApp:housePass@database:27017/houseDB?retryWrites=true&w=majority
      - PORT=5000
      - JWT_SECRET=+j1Q1_VVZDji|mC@m}b;(Cf~K
    ports:
      - "5000:5000"
    depends_on:
      - database

volumes:
  mongodbdata:
    driver: local
